### ISSUE TITLE
Flood game hack

### ISSUE THREAD

**Issue by BlooketHacks123** [Blooket-dude/Blooket-hack#3]
it doesn't work

**Comment by Blooket-dude** [comment]
ok I will try to get a new one becuase the script isn't mine

**Comment by Blooket-dude** [comment]
@BlooketHacks123 Hey im going to delete this hack anyways because you acn get banned if you use it. If your trying to get coins jsut use the max daily tokens and xp. Sorry for the troubles


-Blooket-dude
