### ISSUE TITLE
Can I use your tokens hack if I credit you?

### ISSUE THREAD

**Issue by Hankypoo7** [Blooket-dude/Blooket-hack#4]

**Comment by Blooket-dude** [comment]
That's fine, just give me credits please. You don't have to ask to use anything just make sure to give me credits.

**Comment by Blooket-dude** [comment]
@Hankypoo7 If you use the code give me credits I dont see credits anywhere.

**Comment by Hankypoo7** [comment]
ok i credited you

**Comment by Blooket-dude** [comment]
Thank you Im going to check now @Hankypoo7

**Comment by Hankypoo7** [comment]
ok
