### ISSUE TITLE
Im Usinc Your Hacks

### ISSUE THREAD

**Issue by bigguystevieb1** [Blooket-dude/Blooket-hack#5]
@Blooket-dude Im using ur hacks. OK?

**Comment by bigguystevieb1** [comment]
Im putting them on my repository

**Comment by bigguystevieb1** [comment]
@Blooket-dude

**Comment by bigguystevieb1** [comment]
@Blooket-dude

**Comment by Blooket-dude** [comment]
@bigguystevieb1 make sure to give me credits!

**Comment by Blooket-dude** [comment]
@bigguystevieb1 I would prefer you too not use my hacks. Thank you!
